# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    android: "AIzaSyDGsibOZwMkB9m92TP5qcWPUxpx_zGqU38"

services:
    android.push:
        class: AppBundle\Services\AndroidPush
